BridgeClient/Program.cs
CUIClient/Program.cs
Client/App/IMediatorContext.cs
Client/App/MediatorContext.cs
Client/Peer/Context.cs
Client/Peer/IPeerContext.cs
Client/Peer/Manager/PeerManager.cs
ClientTest/Peer/Manager/PeerManagerRaiseDataEventTest.cs

Implement the EEWTest(beta) event

---

Client/Peer/IPeerContext.cs
EPSPWPFClient/EPSPWPFClient.csproj
EPSPWPFClient/Mediator/EPSPHandler.cs
EPSPWPFClient/Mediator/EPSPMediator.cs
EPSPWPFClient/Userquake/EPSPUQSummaryEventArgs.cs
EPSPWPFClient/Userquake/UQDrawer.cs
EPSPWPFClient/ViewModel/EPSPTitleConverter.cs
EPSPWPFClient/ViewModel/HistoryViewModel.cs

Implement drawing userquake

---

EPSPWPFClient/EPSPWPFClient.csproj
EPSPWPFClient/Mediator/DataHandler.cs
EPSPWPFClient/Mediator/EPSPHandlerFacade.cs
EPSPWPFClient/Mediator/EPSPMediator.cs
EPSPWPFClient/Mediator/IEPSPHandleable.cs
EPSPWPFClient/Mediator/NotifyHandler.cs
EPSPWPFClient/ViewModel/HistoryViewModel.cs

Support balloon notification

---

EPSPWPFClient/PeerMap/Drawer.cs

Improve drawing peermap

---

EPSPWPFClient/Mediator/EPSPMediator.cs
EPSPWPFClient/Userquake/UQDrawer.cs
EPSPWPFClient/ViewModel/HistoryViewModel.cs

Improve drawing userquake

---

Map/Controller/MapDrawer.cs
Map/ImageResource.Designer.cs
Map/ImageResource.resx
Map/Model/MapLoader.cs

```
epsp-peer-cs> .\CLI\bin\Debug\net5.0\CLI map quake --latitude 17.1 --longitude 260.4 --map-type WORLD_512
```
```
epsp-peer-cs> .\CLI\bin\Debug\net5.0\CLI map quake --latitude 17.1 --longitude 260.4 --map-type WORLD_1024
```

Support small world map

---

Client/Peer/State/AbstractState.cs

Fix tsunami packet data length validation

---

WpfClient/Program.cs

Fix information insert order

---

WpfClient/EPSPDataView/EPSPTsunamiView.cs

Format tsunami detail text

---

WpfClient/Notifications/SoundPlayer.cs

Fix error when playing sound

---

AutoUpdater/Updater/UpdateClient.cs
WpfClient/Configuration.cs
WpfClient/Pages/Setting.xaml
WpfClient/Program.cs
WpfClient/SettingViewModel.cs
WpfClient/Updater.cs

Implement autoupdate setting

---

WpfClient/MainWindow.xaml
WpfClient/MainWindow.xaml.cs
WpfClient/Notifications/Activator.cs
WpfClient/Program.cs

Support minimize (in taskbar)

---

Client/App/Userquake/Aggregator.cs
ClientTest/App/Userquake/AggregatorMultithreadTest.cs

Probably make userquake-aggregator more thread-safe

---

WpfClient/Program.cs
WpfClient/WpfClient.csproj

プライバシーポリシーにも記載済み: [プライバシーポリシー · P2P地震情報](https://www.p2pquake.net/privacy_policy/)

Add Sentry

---

WpfClient/Notifications/SoundPlayer.cs

Fix sound playback failing when current directory is different

---

Client/Common/Net/UPnP/UPnPUtil.cs

Ignore UPnP device request error

---

Client/Common/General/Const.cs
Client/Peer/General/PeerConst.cs
Client/Peer/Manager/DuplicateRemover.cs
Client/Peer/Manager/Peer.cs
Client/Peer/Manager/PeerManager.cs
Client/Peer/State/AbstractState.cs
ClientTest/Peer/Manager/PeerManagerTest.cs
ClientTest/Peer/Manager/PeerReadLineTest.cs

- 予約コードの伝達
- 最大経由数の定義変更
Fix #219

Support EPSP v0.35

---

WpfClient/Program.cs

Fix ignoring disconnection complement option

---

WpfClient/Notifications/Notifier.cs

Add magnitude label

---

Client.sln
Client/Peer/State/AbstractState.cs
Map/Model/ObservationAreas.cs
Map/Model/Stations.cs
Map/Model/TsunamiAreas.cs
Map/Model/UserquakeAreas.cs
MapTest/EarthquakeDrawTest.cs
MapTest/Internationalization.cs
MapTest/MapTest.csproj
MapTest/TsunamiDrawTest.cs
MapTest/UserquakeDrawTest.cs
WpfClient/EPSPDataView/EPSPQuakeView.cs
WpfClient/Program.cs

Fix map drawing not to depend on culture

---

Client/App/MediatorContext.cs

Use lock for state operation

---

JsonApi/Client.cs
JsonApi/EEW.cs
JsonApi/JsonApiConverterWithTypeDiscriminator.cs
WpfClient/Program.cs
WpfClient/Utils/EEWConverter.cs

JsonApi, WpfClient: JSON API v2 緊急地震速報（警報）に対応

---

Client/Peer/Manager/Peer.cs
Client/Peer/Manager/PeerManager.cs
Client/Peer/State/AbstractState.cs
ClientTest/Peer/Manager/PeerManagerTest.cs

Disconnect unresponsive peers

---

Client/App/MaintainTimer.cs
Client/App/MediatorContext.cs
Client/App/State/ConnectingState.cs
Client/App/State/MaintenanceState.cs
Client/Client/ClientContext.cs
Client/Client/General/ClientConst.cs
Client/Client/IClientContext.cs

Redo server communication after a long time or in an unexpected state

---

WpfClient/EPSPDataView/EPSPUserquakeView.cs
WpfClient/Pages/Informations/Userquake.xaml

example:
[old_example](https://user-images.githubusercontent.com/1283492/191888175-08bfe519-d386-47c8-a2ac-c78b701c87f8.png)

Add userquake description text

---

WpfClient/Notifications/Notifier.cs
WpfClient/WpfClient.csproj

Retry toast showing and ignore exceptions with Polly

---

CLI/Command/MapCommand.cs
CLI/Command/ServerSubCommand.cs
Map/Controller/MapDrawer.cs

Add map generation server mode (map server subcommand)

---

Client/Common/Net/CRLFSocket.cs
Client/Peer/Manager/PeerManager.cs

Make PeerManager and CRLFSocket thread-safe

---

Client/Client/State/AbstractState.cs

Prevent crash when returning incorrect request error

---

Client/App/IPeerConfig.cs
Client/App/MediatorContext.cs
Client/Peer/IPeerContext.cs
Client/Peer/Manager/PeerManager.cs
Client/Peer/Manager/UserquakeDuplicateRemover.cs
ClientTest/Peer/Manager/PeerManagerRaiseDataEventTest.cs
LambdaMetricsCollector/Function.cs

Remove duplicate userquakes by checking public key

---

Client/App/MaintainTimer.cs
Client/App/MediatorContext.cs
Client/App/State/ConnectingState.cs
Client/App/State/MaintenanceState.cs
Client/Client/ClientContext.cs

Fix incomplete server communication interruption

---

WpfClient/Pages/Status.xaml.cs

Fix license window not redisplaying

---

AutoUpdater/MainWindow.xaml
AutoUpdater/MainWindow.xaml.cs
AutoUpdater/MainWindowModel.cs
AutoUpdater/Program.cs

Update without confirmation if in silent mode

---

WpfClient/MainWindow.xaml
WpfClient/MainWindow.xaml.cs
WpfClient/Pages/Status.xaml
WpfClient/Program.cs
WpfClient/RootViewModel.cs
WpfClient/WpfClient.csproj

Check update in WpfClient

---

Client/App/MediatorContext.cs
WpfClient/EPSPDataView/EPSPEEWView.cs
WpfClient/EPSPDataView/EPSPQuakeView.cs
WpfClient/EPSPDataView/EPSPTsunamiView.cs
WpfClient/EPSPDataView/EPSPUserquakeView.cs
WpfClient/Pages/Information.xaml
WpfClient/Pages/Setting.xaml
WpfClient/Pages/Setting.xaml.cs
WpfClient/Program.cs
WpfClient/SettingViewModel.cs

Add test display button

---

WpfClient/Notifications/SoundPlayer.cs

Play sound again when scale increases

---

WpfClient/InformationViewModel.cs
WpfClient/Pages/Information.xaml
WpfClient/Program.cs

Add loading indicator and faster loading

---

WpfClient/Configuration.cs
WpfClient/InformationViewModel.cs
WpfClient/Pages/Information.xaml
WpfClient/Pages/Information.xaml.cs
WpfClient/Program.cs

Implement tooltips as a tutorial

---

AutoUpdater/MainWindow.xaml.cs
AutoUpdater/P2PQuakeCommunicator.cs
Updater/UpdateClient.cs
WpfClient/Program.cs

Fix to start P2PQuake.exe when update fails

---

WpfClient/Program.cs

Fix Hokkaido userquake not being displayed

---

WpfClient/Notifications/Activator.cs
WpfClient/Notifications/Notifier.cs
WpfClient/Notifications/SoundPlayer.cs
WpfClient/Program.cs

Make event handlers asynchronous for faster notifications

---

WpfClient/Notifications/Notifier.cs

Use UI thread for toast notifications

---

WpfClient/EPSPDataView/EPSPUserquakeView.cs

Hide userquake area when confidence level drops

---

WpfClient/MainWindow.xaml
WpfClient/MainWindow.xaml.cs
WpfClient/Pages/Information.xaml
WpfClient/Pages/Information.xaml.cs

Disable back and forward navigation

---

Map/Model/TsunamiAreasDrawer.cs

Double width of major tsunami warnings

---

Client/App/MediatorContext.cs

Include my userquake in evaluation
